#pragma once

#include"backprop/include.h"
#include"char_pool/include.h"
#include"clean_up/include.h"
#include"codegen/include.h"
#include"common/include.h"
#include"compiler_frontend/include.h"
#include"cuda_kernels/include.h"
#include"cuda_threads/include.h"
#include"data_types/include.h"
#include"libs_llvm/include.h"
#include"math/include.h"
#include"mangler/include.h"
#include"mma/include.h"
#include"networks/include.h"
#include"notators/include.h"
#include"optimizers/include.h"
#include"os/include.h"
#include"processing/include.h"
#include"tensor/include.h"
#include"threads/include.h"